language: go

go:
  - 1.6
  - 1.7

before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/golang/lint/golint
- go get github.com/mattn/goveralls
-  if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
- export PATH=$PATH:$GOPATH/bin

script:
- cd webserver;go test -v -covermode=count -coverprofile=coverage.out;cd ..
- cd browser;go test -v -covermode=count -coverprofile=coverage.out;cd ..
- cd example/browser;go test -v -covermode=count -coverprofile=coverage.out;cd ..
- cd example/webserver;go test -v -covermode=count -coverprofile=coverage.out;cd ..

after_script:
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
- ! golint . 2>&1 | read
- golint .
- ! gofmt -d . 2>&1 | read
- gofmt -d .
